export const FIND_ADDRESSES_BY_ID_REQUEST = 'FIND_ADDRESSES_BY_ID_REQUEST'
export const FIND_ADDRESSES_BY_ID_SUCCESS = 'FIND_ADDRESSES_BY_ID_SUCCESS'
export const FIND_ADDRESSES_BY_ID_FAILURE = 'FIND_ADDRESSES_BY_ID_FAILURE'

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE';

export const FIND_ADDRESS_BY_ID_REQUEST = 'FIND_ADDRESS_BY_ID_REQUEST'
export const FIND_ADDRESS_BY_ID_SUCCESS = 'FIND_ADDRESS_BY_ID_SUCCESS'
export const FIND_ADDRESS_BY_ID_FAILURE = 'FIND_ADDRESS_BY_ID_FAILURE'
